### ISSUE TITLE
We should have a more feature full template 

### ISSUE THREAD

**Issue by majormoses** [Netuitive/chef-netuitive#11]
Right now the Cookbook basically only really supports an api key. It was written in mind to have a separate template that would then be included and merged, due a bug with diamond (and netuitive) this does not work. We will need to add more things to the 'base template'. I do not really know all the things we should be adding and would be helpful to see a real config file used by internal netuitive or an existing customer.

@Createor @shawnbutts if you could produce a sample I can work on getting that into the template. If you want to submit a PR with either an example config file or update the existing config file with some suggestions that would be great.

I would imagine that rather than having an attribute for each value in the config may be rather annoying we may wish to have a single attribute as a hash or something like that. Once I see what a example config file looks like we can make a decision on that.

**Comment by shawnbutts** [comment]
Here are some example config files.  https://gist.github.com/shawnbutts/3ee01e969a259da77b02

As you can see, most of the complexity around automating the config is in the collectors section.  They are a wide range of collector (including custom ones) and each has there own set of config options and requirements.

**Comment by majormoses** [comment]
@shawnbutts I see that each collector has its own config file, does that mean that collectors can have their own files? If so that part is greatly simplified. What other config do we need to worry about other than collectors?

**Comment by shawnbutts** [comment]
The files in the gist are from different types of servers.  But, they each are the full single netuitive-agent.conf file

For the moment, we only support a single config file.  Eventually, we will support 1 file per collector as well.  

We should also worry about the settings in under the "[[NetuitiveHandler]]" section.

**Comment by majormoses** [comment]
ew...ok lets start with the basic and then we will do one collector at a time...ugh...logic in templates make me sad...

**Comment by majormoses** [comment]
@shawnbutts what happens if you specify a value multiple times? for example:

```
tags = tag1:thing1
tags = tag2:thing2
```

**Comment by shawnbutts** [comment]
I'm not sure what would happen.  But, it wouldn't be supported whatever it is. :)

**Comment by majormoses** [comment]
@shawnbutts @Createor I was thinking about this more and even if we must at the end of the day have one massive config it doesnt mean we have to manage it as a single template. I was thinking we have a template for each collector and then have some logic based on say an array of collectors you pass it concat those templates together during the chef run. What are your thoughts on this? We do lose idempotency but at the cost of managing one super template with potentially 40+ collectors this may seem the way to go...I am still not sure what I think about this...

**Comment by shawnbutts** [comment]
It sounds reasonable to me.  My only concern is maintaining the templates for so many collectors.  Especially when many on them will just have an "enabled = true" setting.

**Comment by majormoses** [comment]
@shawnbutts I assume we cant merge collectors in the same file either right?

example:

```
    [collectors]
    [[default]]
    [[CPUCollector]]
    enabled = True
    percore = False
    include_cpu_pct = True
```

and this appended to the end

```
    [collectors]
    [[default]]
    [[CPUCollector]]
    enabled = False
    percore = False
    include_cpu_pct = True
```

**Comment by shawnbutts** [comment]
Correct.  There can be only one [[CPUCollector]] as well as only one [collectors].  You can think []'s as different levels in the config.  if it were YAML, it would be like this.

collectors:
  default:
  CPUCollector:
    enabled: True
    percore: False
    include_cpu_pct: True

Really, the whole config file get's read into a Python dictionary.  But, for simplicity, I like to think of it in YAML.

**Comment by majormoses** [comment]
@shawnbutts I am not crazy about this idea either but what about having the whole collectors section be passed in as a hash and having the hash be constructed by chef attributes if you don't want to specify a nice big hash with the provider?

The attributes might look something like this:

```
default['netuitive']['collectors']['CPUCollector']['enabled'] = true
default['netuitive']['collectors']['CPUCollector']['percore'] = true

default['netuitive']['collectors']['NetworkCollector']['enabled'] = true
default['netuitive']['collectors']['NetworkCollector']['metrics_whitelist'] = '(?:^.*\.rx_byte$|^.*\.rx_errors$|^.*\.rx_packets$|^.*\.tx_byte$|^.*\.tx_errors$|^.*\.tx_packets$)'
```

then in a lwrp we would construct the hash like this:

```
collectors = node['netuitive']['collectors'].to_h
```

pass the hash to the template:

```
    template new_resource.conf_path do
      source new_resource.source
      cookbook new_resource.cookbook_template
      variables(
        api_key: new_resource.api_key,
        api_url: new_resource.api_url,
        tags: new_resource.tags,
        relations: new_resource.relations,
        collectors collectors
      )
```

the template would have a section like this:

```
<% @collectors.each do |collector, options| %>
  [[<%collector%>]]
  <% options.each do |k,v| %>
     <% k %> = <% v %>
  <% end %>
<% end %>
```

At the end of the day until we can manage the templates as individual files I dont see a good solution...I am open to ideas...

**Comment by shawnbutts** [comment]
That should work more most collectors.  Some of them have at least 1 more layer of []'s.  

I agree that the individual files is the way to go.  Hopefully, that will be possible in the next few releases.

**Comment by majormoses** [comment]
@shawnbutts yup...I was trying to find something for the interim but we might just want to wait until that is fixed...we cant cover every scenario without maintaining a massive template...

**Comment by shawnbutts** [comment]
With the next release of the agent additional collectors can have their own config files in /opt/netuitive-agent/conf/collectors/.  The file name is used as the collector name and the contents will have fewer [] levels.  This should allow us to have templates per collector.

Example:
/opt/netuitive-agent/conf/collectors/HttpdCollector.conf

> enabled = False
> urls = localhost http://localhost:8080/server-status?auto

@majormoses, what are your thoughts on the best way to add this capability to this cookbook?

**Comment by majormoses** [comment]
@shawnbutts very nice this will immensely simplify things, I have a couple of questions and some thoughts. With regards to the new setup will it still look like this:

```
[collectors]
[[httpd]]
enabled = False
urls = localhost http://localhost:8080/server-status?auto
```

while this is a simple example I remember there being nested collectors how would that work?

 I see two possible options and we may end up using both depending on complexity and how much we want to maintain:
- use a generic template that you could pass a hash (or some other data structure) to that we could construct the collector from it
- have a template for a collector

I am thinking we have some combination of the two. As a maintainer it might be difficult to have 40+ templates and fulfill every scenario a customer may want. On the other hand we need flexibility where the template may just have too much complexity that it is undesirable to attempt to cover all the specific logic in the generic template. That being said if we are willing to invest the time to have a template for each it does make a newcomer to netuitive have a much better 'quickstart' as they have no idea what they want yet. 

Interested on your thoughts as well as it will be freeing you from the same problem and our approach will likely want to be the same in your salt and chef.

**Comment by shawnbutts** [comment]
My thought was to have the default collectors Netuitive needs in the netuitive-agent.conf file and the user configurable one in the individual files.  The nesting stays for our stuff, and goes away for the user's collectors.

I think that lines up with your idea of user supplied hash with a generic collector template. If it turns out that the the hash approach is too complex to manage, we can always move to template per collector. 

Hopefully, the next version of the agent will be out next week.  If we're in agreement with this approach, I'll submit a PR with some minor changes at the same time.  If it looks good, we can use that as the base for these changes. 

Thoughts?

**Comment by majormoses** [comment]
@shawnbutts overall sounds reasonable just a quick clarification 

> The nesting stays for our stuff, and goes away for the user's collectors.

You mean that **netuitive** collectors will have nesting while others will not?

**Comment by shawnbutts** [comment]
The 8 default collectors (listed below) would stay in the netuitive-agent.conf file as they are today (nested).
- CPUCollector
- DiskSpaceCollector
- DiskUsageCollector
- LoadAverageCollector
- MemoryCollector
- VMStatCollector
- NetworkCollector
- NetuitiveDockerCollector

Any others would go in the /opt/netuitive-agent/conf/collectors/ directory, one file per collector.  These files would not have the top 2 layers of nesting.  A few collectors will still require some nesting.

**Comment by majormoses** [comment]
@shawnbutts thanks for the clarification, reading back this makes more sense now

**Comment by majormoses** [comment]
@shawnbutts I assume that the new release will have those 8 default in the agent conf that is delivered by the package installer right? I don't believe that those are all included currently. I would like our agent template to mirror what the package deploys as much as possible.

**Comment by shawnbutts** [comment]
Correct.  My PR will include the changes to bring the template here inline with the new default config for the agent.

**Comment by shawnbutts** [comment]
https://github.com/Netuitive/chef-netuitive/pull/19

**Comment by majormoses** [comment]
@shawnbutts now that https://github.com/Netuitive/chef-netuitive/pull/19 has landed we should be able to do seperate collector configs now?

Do you have some bandwidth to implement this as we discussed? If not I can try to get to it though I doubt I will have the bandwidth until next week.

**Comment by shawnbutts** [comment]
I doubt I will have the bandwidth before next month.

**Comment by majormoses** [comment]
@shawnbutts I notice that https://repos.app.netuitive.com/deb is not crawlable, how do we expect people to know when new versions come out?

**Comment by shawnbutts** [comment]
We do announce new agents at https://github.com/Netuitive/omnibus-netuitive-agent/releases.

We're looking at options for making the repo crawler friendly.

**Comment by majormoses** [comment]
@shawnbutts what is the `-95` then? `0.2.6-95` is the version we have in the cookbook but I see nothing in the release page in github to show this...

**Comment by shawnbutts** [comment]
It's the build number.

**Comment by majormoses** [comment]
@shawnbutts where would someone external find that?
