### ISSUE TITLE
Typo: use_epl_repos should be use_epel_repos

### ISSUE THREAD

**Issue by ziggythehamster** [Netuitive/chef-netuitive#37]
The typo is the same on the resource and the provider, so it works if you use the typo'ed attribute.

**Comment by majormoses** [comment]
@ziggythehamster I would say looking at this that it was probably a doc issue but I think I like epel vs epl anyways so I dont mind changing it, I will  have a fix shortly.

**Comment by majormoses** [comment]
@ziggythehamster this should be fixed as soon as https://github.com/Netuitive/chef-netuitive/pull/38 lands
