### ISSUE TITLE
Moderate severity security vulnerability detected in rack

### ISSUE THREAD

**Issue by yadima** [Netuitive/chef-netuitive#58]
Received a security alert:
Known moderate severity security vulnerability detected in rack >= 2.0.0, < 2.0.6 defined in Gemfile.lock.
Gemfile.lock update suggested: rack ~> 2.0.6.
https://github.com/Netuitive/chef-netuitive/network/alert/Gemfile.lock/rack/open

**Comment by majormoses** [comment]
Thanks for reporting this is only something that affects local development and would never be part of what is uploaded to the chef server. Pretty sure we can blindly bump the dependency.

**Comment by majormoses** [comment]
As this is now merged into master as per #67 and it only affects development in a very specific set of circumstances I am not gonna make a release until there is an actual behavioral change but will call this good.
