### ISSUE TITLE
Chef Support Updates and CI fixes

### ISSUE THREAD

**Issue by majormoses** [Netuitive/chef-netuitive#62]
We need to drop chef 12 and 13 compatibility due to maintainability. See https://github.com/Netuitive/chef-netuitive/pull/61#issuecomment-504543833 for more details.

Make some decisions and document support, this includes outlining new branching strategies and expectations.

Fix ci

EDIT: based on the feedback here is a list of action items:
- [x] create branches for `chef-client/11.x`, `chef-client/12.x`, and `chef-client/13.x`.
- [x] These branches should be setup to be protected to prevent accidental deletion and such.
- [x] update in master readme documentation to help highlight these changes
- [x] remove chef 13 compatibility (depending on what version of 13.x you have you may already be broken but we can't control when upstream does breaking changes outside of major versions)
- [x] fixup CI

**Comment by majormoses** [comment]
Given that currently chef does not support `< 14.x` anymore I think we should drop it: https://docs.chef.io/versions.html#end-of-life-eol-products. This cookbook was originally written in chef 12 days and ported limited functionality back to chef 11. We have continued to support both chef 12 and 13 for a very long time and its time we break compatibility. However we can do it in a way that allows continued development and maintenance on legacy code with purely community contributions.

In order to allow people to continue to use this cookbook regardless of the limitations within their orgs we are going to make some changes regarding legacy versions of this cookbook. Previously chef 11 support existed in `feature/chef-11-compatibility` branch, I think using `chef-client/$MAJOR` or something along those lines to indicate when we no longer aim to maintain compatibility with a version of `chef-client`. Releases on github and supermarket will only be made from master which should reflect the latest version of chef that is supported. All other versions must be pulled from github branches. This is in part to avoid conflicts with versioning as we follow semver and do not want to tie our hands or make our versions confusing to users.

This would result in the creation of:
- `chef-client/11.x`: no longer supported
- `chef-client/12.x`: no longer supported
- `chef-client/13.x`: no longer supported

The master branch will be geared toward chef 14 until it is no longer supported, will be bumped to 15, etc.

Let me know what you think.

**Comment by majormoses** [comment]
@ziggythehamster @rclagett could you two weigh in here?

**Comment by rclagett** [comment]
This makes a lot of sense to me, and I'm on board with it. I like the idea of backwards compatibility branches for folks using the cookbook who haven't yet updated chef. Than you so much for the dedication @majormoses!

**Comment by ziggythehamster** [comment]
I'm happy with this. Basically the main breakages aren't even in Chef syntax, but in the standard library.

**Comment by majormoses** [comment]
@rclagett it looks like I dont have enough access to make the `chef-client/*` branches protected can you please enable those protections?

EDIT: once that has been done and #65 is merged and released this can be closed.

**Comment by rclagett** [comment]
@majormoses I increased your access level. Could you give it another try?

**Comment by majormoses** [comment]
@rclagett that worked for me, thank you.

https://github.com/Netuitive/chef-netuitive/settings/branch_protection_rules/5738962

For right now I enabled the basic protections and used a pattern to ensure that newly created branches following that pattern will auto be protected.

![image](https://user-images.githubusercontent.com/3145127/60443958-1ab43a80-9bd1-11e9-8029-035fcc16c3f3.png)


![image](https://user-images.githubusercontent.com/3145127/60443988-269ffc80-9bd1-11e9-9550-95612195e7fa.png)

**Comment by rclagett** [comment]
@majormoses This is great! Really appreciate you setting it all up.

**Comment by majormoses** [comment]
released: https://supermarket.chef.io/cookbooks/netuitive/versions/1.0.0
